### ISSUE TITLE
python3.5

### ISSUE THREAD

**Issue by wethegreenpeople** [pettazz/pygooglevoice#23]
Hi! Is pygooglevoice working with python3.5? I'm getting this error when I try and run it in python3.5 `File "voice.py", line 1, in <module>
    from googlevoice import Voice
  File "/usr/local/lib/python3.5/dist-packages/googlevoice/__init__.py", line 17, in <module>
    from voice import Voice
  File "/home/ubuntu/voice/voice.py", line 1, in <module>
    from googlevoice import Voice
ImportError: cannot import name `'Voice'``

Otherwise it works fine for me!

**Comment by tom-slick** [comment]
Your file is named voice.py, that's the same as the module you are trying to import.  Rename /home/ubuntu/voice/voice.py to something else.

**Comment by woodyl** [comment]
I had to make significant changes in several of the modules to get pygooglevoice working under Python3.  Even after you get it to load, you will probably run into some more errors.

**Comment by chris001** [comment]
@woodyl 
Care to contribute your working under Python3 version back as a pull request?

**Comment by woodyl** [comment]
@chris001
When I get the time, I'll organize the changes and put them up here.

**Comment by chris001** [comment]
@woodyl  A tip if you want an app to help organize the changes for 3.5, try the free community edition of PyCharm, it's good. https://www.jetbrains.com/pycharm/download/

**Comment by woodyl** [comment]
@chris001  Thanks, I'll take a look at it.

**Comment by jaraco** [comment]
Feel free to give [googlevoice](https://pypi.org/project/googlevoice) a try. It has [CI tests](https://travis-ci.org/jaraco/googlevoice) even [on Windows](https://ci.appveyor.com/project/jaraco/googlevoice) demonstrating working functionality on Python 2.7 and 3.6 and 3.7.

**Comment by jaraco** [comment]
Following the acceptance of #56, this issue should be fixed now.
